[package]
name = "choppo"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "6.1.1"
ffmpeg-sys-next = "6.1.0"
sdl2 = "0.36.0"
nom = "7.1.3"
fraction = "0.15.1"
filetime = "0.2"
tokio={version = "1.36.0", features=["sync", "macros", "rt-multi-thread"]}

[profile.release]
debug = true
